### ISSUE TITLE
Rationale for ecdh_skip_hash_extract_x_and_y

### ISSUE THREAD

**Issue by mikekelly** [Sajjon/K1#1]
This libarary is great, I really like the minimalist API but I'm having interoperability issues using it for ECDH. 

I believe it is due to `PrivateKey.sharedSecret` using ecdh_skip_hash_extract_x_and_y

https://github.com/Sajjon/K1/blob/89cac3e2f7765f4a782ae71d2de231c08dcfaa53/Sources/K1/K1/Keys/PrivateKey/PrivateKey/PrivateKey%2BBridge%2BTo%2BC.swift#L144

The result is Data that when put through `SHA256.hash` produces a inconsistent result from libraries like this:

https://github.com/bitcoin-core/secp256k1/blob/185a6af22792531a629959834fff9257e396abb5/src/modules/ecdh/main_impl.h#L13-L24

I was wondering if this was an intentional design decision and what the rationale was?

**Comment by mikekelly** [comment]
yeah, combined with an enum of the available functions (defaulting to `. ecdh_skip_hash_extract_x_and_y`, so the API doesn't break) would be a nice API :)

**Comment by Sajjon** [comment]
@mikekelly First of all, so so sorry for slowest response every! I was busy with other work. In https://github.com/Sajjon/K1/pull/7 I've solved this issue, I now vendor three different ECDH variants, one of which is `CryptoKit` compatible, because it returns `CryptoKit`'s [`SharedSecret` struct](https://developer.apple.com/documentation/cryptokit/sharedsecret) which is really nice, since offers KDFs!

One which follows standards `libsecp256k1` and lastly the old one (custom, no hash), please see the PR https://github.com/Sajjon/K1/pull/7 for details. 

I will make a new release `0.0.9` with these new APIs
