### ISSUE TITLE
Using playground I have problem

### ISSUE THREAD

**Issue by dannpr** [Sajjon/K1#39]
Missing required module 'secp256k1' when I'm beginning to code the package on SPI playground, can you help me resolve this

```swift

import K1
let alice = K1.ECDSA.PrivateKey()
```

**Comment by Sajjon** [comment]
@dannpr hey! I dont think K1 will work in a playground. 

Instead you can create a tiny Swift Package and "play" with K1 in a unit test target of your package.

**Comment by dannpr** [comment]
oh ok thanks ! I've found a way to make it work but I'd like to generate a standard public key like 0x... is there a truc because only let `swift
alicePublicKey = alice.publicKey` give me this `bash
PublicKey(impl: K1.K1._PublicKeyImplementation(wrapped: K1.FFI.PublicKey.Wrapped(raw: __C.secp256k1_pubkey(data: (35, 77, 102, 27, 209, 204, 77, 182, 30, 12, 119, 5, 48, 97, 255, 242, 78, 88, 53, 176, 225, 67, 117, 200, 16, 44, 115, 143, 109, 146, 236, 13, 161, 176, 28, 46, 132, 241, 48, 162, 91, 207, 230, 113, 204, 73, 235, 117, 192, 116, 187, 63, 213, 175, 137, 101, 67, 66, 167, 247, 110, 180, 102, 102)))))
`

**Comment by Sajjon** [comment]
> Ho and another question are you using secure enclave ? Because my goal is to use secure enclave. I know that cryptokit is using it

You can't. No third party library author can make use of SecureEnclave as you intend to. [CryptoKit ONLY supports signing with SecureEnclave for the curve `P256`](https://developer.apple.com/documentation/cryptokit/secureenclave/p256/signing/privatekey) (aka `secp256r1` (notice `r` instead of `k`)) it does **not** even support SecureEnclave usage for the [other curves in CryptoKit, e.g. `Curve25519`](https://developer.apple.com/documentation/cryptokit/curve25519).

What "using Secure enclave" really means is that the signing takes place on the secure chip, and that it is impossible to read out the private key from the chip. You can only do that with `P256`.

**Comment by dannpr** [comment]
Thanks a lot ! I'm using K1 and everything seems to work well, thanks ! 
Lasts questions, I hope I can make sense : 
1. I see that even if I'm doing `let privateKey = K1.ECDSA.PrivateKey() ` I cannot have access to the private key of the key pair, right ? 
2. About secure enclave, I can first authenticate the user with faceID by using secure enclave and then use your package to create a keypair on the K1 curve , verify and sign data right ? And store on Keychain the public key. 

thanks again for your responce
